2025-09-24 05:12:13,922 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:12:13,923 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:12:14,023 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:12:14,026 - uvicorn.error - INFO - Started server process [9868] [server.py:84]
2025-09-24 05:12:14,026 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:12:14,027 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:12:17,158 - app.routers.users - INFO - Attempting to register user with email: testerwizard02@gmail.com and username: tester [users.py:17]
2025-09-24 05:12:17,176 - app.routers.users - ERROR - Registration failed for testerwizard02@gmail.com: type object 'User' has no attribute 'username' [users.py:101]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/app/routers/users.py", line 21, in register_user
    (models.User.email == user.email) | (models.User.username == user.username)
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'User' has no attribute 'username'
2025-09-24 05:14:47,615 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 05:14:47,716 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 05:14:47,716 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 05:14:47,716 - uvicorn.error - INFO - Finished server process [9868] [server.py:94]
2025-09-24 05:14:52,204 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:14:52,204 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:14:52,310 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:14:52,312 - uvicorn.error - INFO - Started server process [10383] [server.py:84]
2025-09-24 05:14:52,313 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:14:52,313 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:14:55,859 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:14:55,859 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:14:55,949 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:14:55,952 - uvicorn.error - INFO - Started server process [10426] [server.py:84]
2025-09-24 05:14:55,952 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:14:55,953 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:14:59,366 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:14:59,367 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:14:59,457 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:14:59,459 - uvicorn.error - INFO - Started server process [10470] [server.py:84]
2025-09-24 05:14:59,459 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:14:59,460 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:15:28,772 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 05:15:28,874 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 05:15:28,883 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 05:15:28,884 - uvicorn.error - INFO - Finished server process [10470] [server.py:94]
2025-09-24 05:15:34,104 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:15:34,104 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:15:34,204 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:15:34,205 - uvicorn.error - INFO - Started server process [10549] [server.py:84]
2025-09-24 05:15:34,206 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:15:34,206 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:15:44,340 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 05:15:44,442 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 05:15:44,442 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 05:15:44,442 - uvicorn.error - INFO - Finished server process [10549] [server.py:94]
2025-09-24 05:21:27,144 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:21:27,145 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:21:27,214 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:21:27,215 - uvicorn.error - INFO - Started server process [11119] [server.py:84]
2025-09-24 05:21:27,216 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:21:27,216 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:21:29,603 - app.routers.users - INFO - Attempting to register user with email: testerwizard02@gmail.com and username: tester [users.py:17]
2025-09-24 05:21:29,634 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 05:21:30,047 - app.routers.users - INFO - User registered successfully: testerwizard02@gmail.com [users.py:87]
2025-09-24 05:21:35,628 - app.routers.users - INFO - Welcome email sent to: testerwizard02@gmail.com [users.py:92]
2025-09-24 05:22:28,310 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 05:22:28,681 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 05:22:28,736 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:22:29,099 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:22:44,027 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:22:46,043 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:22:47,396 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:24:34,215 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 05:24:34,316 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 05:24:34,318 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 05:24:34,318 - uvicorn.error - INFO - Finished server process [11119] [server.py:94]
2025-09-24 05:25:47,719 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:25:47,720 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:25:47,799 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:25:47,800 - uvicorn.error - INFO - Started server process [11671] [server.py:84]
2025-09-24 05:25:47,801 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:25:47,801 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:25:48,465 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 05:25:48,496 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 05:25:48,853 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 05:25:48,863 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:25:49,056 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:29:50,988 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 05:29:51,340 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 05:29:51,358 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:29:51,543 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:34:03,342 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 05:34:03,443 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 05:34:03,444 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 05:34:03,444 - uvicorn.error - INFO - Finished server process [11671] [server.py:94]
2025-09-24 05:42:26,060 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 05:42:26,061 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 05:42:26,246 - app.main - INFO - API routers included [main.py:53]
2025-09-24 05:42:26,250 - uvicorn.error - INFO - Started server process [14697] [server.py:84]
2025-09-24 05:42:26,250 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 05:42:26,251 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 05:42:30,783 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 05:42:30,856 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 05:42:31,589 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 05:42:31,623 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:42:31,952 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:43:15,790 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 05:43:16,475 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 05:43:16,495 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:43:16,811 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:45:16,751 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:45:18,431 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:45:20,076 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:45:21,616 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:45:23,032 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 05:45:27,837 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:173]
2025-09-24 06:02:13,570 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:02:14,074 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 06:02:40,616 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 06:02:40,718 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 06:02:40,720 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 06:02:40,720 - uvicorn.error - INFO - Finished server process [14697] [server.py:94]
2025-09-24 06:02:48,093 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:02:48,093 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:02:48,173 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:02:48,175 - uvicorn.error - INFO - Started server process [17772] [server.py:84]
2025-09-24 06:02:48,175 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:02:48,176 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:02:52,337 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:02:52,444 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 06:02:52,879 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 06:02:57,945 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:02:58,280 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 06:08:12,441 - app.routers.users - INFO - Attempting login for user: testterwizard02@gmail.com [users.py:114]
2025-09-24 06:08:12,442 - app.routers.users - WARNING - Login failed: User with email testterwizard02@gmail.com not found [users.py:119]
2025-09-24 06:08:20,294 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:08:20,647 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:155]
2025-09-24 06:22:03,523 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 06:22:03,625 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 06:22:03,627 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 06:22:03,627 - uvicorn.error - INFO - Finished server process [17772] [server.py:94]
2025-09-24 06:22:11,092 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:22:11,093 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:22:11,250 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:22:11,254 - uvicorn.error - INFO - Started server process [19243] [server.py:84]
2025-09-24 06:22:11,255 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:22:11,257 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:22:15,706 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:22:15,707 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:22:15,831 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:22:15,834 - uvicorn.error - INFO - Started server process [19306] [server.py:84]
2025-09-24 06:22:15,836 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:22:15,836 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:22:26,092 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 06:22:26,194 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 06:22:26,194 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 06:22:26,194 - uvicorn.error - INFO - Finished server process [19306] [server.py:94]
2025-09-24 06:22:32,492 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:22:32,493 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:22:32,640 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:22:32,643 - uvicorn.error - INFO - Started server process [19355] [server.py:84]
2025-09-24 06:22:32,644 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:22:32,644 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:23:14,641 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 06:23:14,742 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 06:23:14,743 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 06:23:14,749 - uvicorn.error - INFO - Finished server process [19355] [server.py:94]
2025-09-24 06:23:19,386 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:23:19,387 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:23:19,490 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:23:19,491 - uvicorn.error - INFO - Started server process [19503] [server.py:84]
2025-09-24 06:23:19,491 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:23:19,492 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:23:36,468 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:23:36,531 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 06:23:36,889 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:160]
2025-09-24 06:27:31,126 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:27:31,495 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:160]
2025-09-24 06:27:48,084 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:27:48,086 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:13,736 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:31:14,084 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:160]
2025-09-24 06:31:14,150 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,153 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,209 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:14,366 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,370 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,380 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,383 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,411 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:14,416 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,419 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,439 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:14,499 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:14,533 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,535 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,549 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,552 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,583 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:14,600 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,602 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:14,714 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:14,716 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:28,190 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:28,206 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:28,232 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:28,247 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:28,248 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:28,253 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:28,334 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:28,455 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:28,458 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,496 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,506 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,512 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,514 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,545 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,552 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,564 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:40,577 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:40,615 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:40,675 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,678 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,708 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,710 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,722 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,727 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:40,770 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:31:40,893 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:31:40,894 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:31:57,882 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 06:31:57,982 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 06:31:57,983 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 06:31:57,983 - uvicorn.error - INFO - Finished server process [19503] [server.py:94]
2025-09-24 06:32:04,039 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:32:04,040 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:32:04,113 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:32:04,115 - uvicorn.error - INFO - Started server process [20698] [server.py:84]
2025-09-24 06:32:04,115 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:32:04,115 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:32:06,934 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:32:06,989 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 06:32:07,350 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:160]
2025-09-24 06:32:07,403 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,405 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,454 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:32:07,647 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,650 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,651 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,656 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,670 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,673 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,698 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:32:07,715 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:32:07,728 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:32:07,793 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,796 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,811 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,812 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,826 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,827 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:07,862 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:32:07,961 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:07,963 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:30,428 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:30,432 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:30,444 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:30,448 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:30,450 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:30,459 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:30,521 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:32:30,661 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:32:30,663 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:32:59,850 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-24 06:32:59,951 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-24 06:32:59,952 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-24 06:32:59,953 - uvicorn.error - INFO - Finished server process [20698] [server.py:94]
2025-09-24 06:33:05,954 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-24 06:33:05,955 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-24 06:33:06,066 - app.main - INFO - API routers included [main.py:53]
2025-09-24 06:33:06,069 - uvicorn.error - INFO - Started server process [20899] [server.py:84]
2025-09-24 06:33:06,069 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-24 06:33:06,070 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-24 06:33:06,862 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:114]
2025-09-24 06:33:06,899 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-24 06:33:07,263 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:160]
2025-09-24 06:33:07,326 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,328 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,377 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:33:07,531 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,534 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,544 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,548 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,561 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:33:07,579 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,584 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,621 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:33:07,637 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:33:07,663 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,665 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,729 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,730 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,737 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,739 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:07,805 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:33:07,908 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:07,910 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:23,020 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:23,030 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:23,038 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:23,041 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:23,042 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:23,046 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-24 06:33:23,104 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:213]
2025-09-24 06:33:23,254 - app.routers.users - INFO - Attempting to refresh access token [users.py:182]
2025-09-24 06:33:23,255 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:192]
2025-09-25 22:19:24,095 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-25 22:19:24,159 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-25 22:19:24,289 - app.main - INFO - API routers included [main.py:53]
2025-09-25 22:19:24,292 - uvicorn.error - INFO - Started server process [144952] [server.py:84]
2025-09-25 22:19:24,293 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-25 22:19:24,293 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-25 22:19:28,967 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:19:29,004 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-09-25 22:19:29,884 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:19:29,885 - uvicorn.error - ERROR - Exception in ASGI application
 [h11_impl.py:408]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/fastapi/routing.py", line 328, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eddy/Documents/we_page/Blackgem-project/black_germ_backend/venv/lib/python3.12/site-packages/fastapi/routing.py", line 177, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', 'refresh_token'), 'msg': 'Field required', 'input': {'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0ZXJ3aXphcmQwMkBnbWFpbC5jb20iLCJleHAiOjE3NTg4MzY5Njl9.Ray9bpBc4j6aPC6sPKM87tkyx8LjNOwqBqpg37pp7lY', 'token_type': 'bearer'}}

2025-09-25 22:21:54,997 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-25 22:21:55,098 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-25 22:21:55,099 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-25 22:21:55,099 - uvicorn.error - INFO - Finished server process [144952] [server.py:94]
2025-09-25 22:24:16,934 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-25 22:24:16,956 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-25 22:24:17,177 - app.main - INFO - API routers included [main.py:53]
2025-09-25 22:24:17,179 - uvicorn.error - INFO - Started server process [145930] [server.py:84]
2025-09-25 22:24:17,179 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-25 22:24:17,180 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-25 22:24:38,581 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:24:39,787 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:24:40,395 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:24:42,618 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:24:42,624 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:24:43,341 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:24:43,448 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:24:43,518 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:24:43,654 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:24:56,571 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:24:56,574 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:24:56,586 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:24:56,593 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:24:57,391 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:24:57,404 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:26:41,995 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:26:41,999 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:26:42,011 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:26:42,019 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:26:42,495 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:26:42,528 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:26:54,210 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-25 22:26:54,311 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-25 22:26:54,312 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-25 22:26:54,312 - uvicorn.error - INFO - Finished server process [145930] [server.py:94]
2025-09-25 22:27:01,306 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-25 22:27:01,306 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-25 22:27:01,389 - app.main - INFO - API routers included [main.py:53]
2025-09-25 22:27:01,391 - uvicorn.error - INFO - Started server process [146318] [server.py:84]
2025-09-25 22:27:01,392 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-25 22:27:01,392 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-25 22:27:18,655 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:27:19,086 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:27:19,101 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:19,261 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:27:19,268 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:27:19,287 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:19,303 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:19,360 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:19,443 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:26,256 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:27:26,264 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:27:26,274 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:27:26,277 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:27:26,435 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:26,446 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:40,975 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:27:41,290 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:27:41,299 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:41,413 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:27:41,416 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:27:41,549 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:41,606 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:41,665 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:41,877 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:46,519 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:27:46,521 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:27:46,529 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:27:46,534 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:27:46,669 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:27:46,686 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:31,721 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:38:32,242 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:38:32,256 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:32,428 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:32,429 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:38:32,433 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:38:32,454 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:32,487 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:32,607 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:34,046 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:38:34,050 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:38:34,059 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:38:34,073 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:38:34,192 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:38:34,207 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:37,580 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:39:38,069 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:39:38,083 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:38,226 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:39:38,229 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:39:38,238 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:38,265 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:38,282 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:38,330 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:39,583 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:39:39,585 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:39:39,588 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:39:39,592 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:39:39,624 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:39:39,648 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:40:09,698 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-25 22:40:09,799 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-25 22:40:09,800 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-25 22:40:09,800 - uvicorn.error - INFO - Finished server process [146318] [server.py:94]
2025-09-25 22:40:41,155 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-25 22:40:41,156 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-25 22:40:41,350 - app.main - INFO - API routers included [main.py:53]
2025-09-25 22:40:41,351 - uvicorn.error - INFO - Started server process [147545] [server.py:84]
2025-09-25 22:40:41,351 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-25 22:40:41,352 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-25 22:41:02,655 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:41:03,225 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:41:03,255 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:41:03,464 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:41:03,469 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:41:03,493 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:41:03,504 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:41:03,524 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:41:03,661 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:41:06,569 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:41:06,578 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:41:06,582 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:41:06,584 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:41:06,737 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:41:06,755 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:51:27,207 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:51:27,704 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:51:27,716 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:51:28,014 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:51:28,018 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:51:28,077 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:51:28,090 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:19,291 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:55:19,673 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:55:19,691 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:19,882 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:19,893 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:19,912 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:20,148 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:26,564 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:55:26,578 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:55:26,610 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:55:26,618 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:55:26,979 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:26,999 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:55,487 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 22:55:55,793 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 22:55:55,808 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:56,018 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:56,035 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:56,074 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:55:56,225 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:56:09,496 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:56:09,498 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:56:09,521 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 22:56:09,533 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 22:56:09,941 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 22:56:09,955 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:02:57,185 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-25 23:02:57,287 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-25 23:02:57,288 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-25 23:02:57,288 - uvicorn.error - INFO - Finished server process [147545] [server.py:94]
2025-09-25 23:03:07,667 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-25 23:03:07,668 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-25 23:03:07,754 - app.main - INFO - API routers included [main.py:53]
2025-09-25 23:03:07,755 - uvicorn.error - INFO - Started server process [150093] [server.py:84]
2025-09-25 23:03:07,756 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-25 23:03:07,756 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-25 23:07:40,099 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 23:07:40,756 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 23:07:40,776 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:07:40,976 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:07:40,985 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:07:40,994 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:07:41,228 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:07:46,574 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 23:07:46,577 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 23:07:46,642 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:09:54,497 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 23:09:54,811 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 23:09:54,831 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:09:55,011 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:09:55,019 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:09:55,053 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:09:55,117 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:10:44,391 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 23:10:44,395 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 23:10:44,457 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:29,366 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 23:36:30,453 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 23:36:30,657 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:31,410 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:31,517 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:31,614 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:31,977 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:36,862 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:40,014 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:42,628 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:44,644 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:44,668 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:44,701 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:45,075 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:49,938 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 23:36:49,960 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 23:36:50,074 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:50,508 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:36:50,574 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:37:14,560 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 23:37:14,566 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 23:37:14,649 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:37:14,976 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:37:15,132 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:39:05,052 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-25 23:39:05,072 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-25 23:39:05,159 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:39:05,486 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:39:05,517 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:43,204 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:43,333 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:43,531 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:43,823 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:46,527 - app.routers.users - INFO - Attempting to log out user [users.py:245]
2025-09-25 23:43:46,530 - app.routers.users - INFO - User logged out successfully [users.py:253]
2025-09-25 23:43:55,054 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 23:43:56,213 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 23:43:56,345 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:57,286 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:57,384 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:57,480 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:43:57,654 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:44:03,204 - app.routers.users - INFO - Attempting to log out user [users.py:245]
2025-09-25 23:44:03,206 - app.routers.users - INFO - User logged out successfully [users.py:253]
2025-09-25 23:56:32,895 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-25 23:56:33,212 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-25 23:56:33,223 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:56:33,369 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:56:33,379 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:56:33,398 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:56:33,474 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:59:52,907 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:59:52,950 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:59:52,988 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:59:53,040 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-25 23:59:56,462 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-26 00:01:12,455 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-26 00:01:12,473 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-26 00:01:12,503 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-26 00:01:12,577 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-26 00:01:28,824 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-26 07:44:13,146 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-26 07:44:13,314 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-26 07:44:13,397 - app.main - INFO - API routers included [main.py:53]
2025-09-26 07:44:13,400 - uvicorn.error - INFO - Started server process [165000] [server.py:84]
2025-09-26 07:44:13,400 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-26 07:44:13,401 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-28 13:00:05,864 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-28 13:00:05,898 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-28 13:00:06,005 - app.main - INFO - API routers included [main.py:53]
2025-09-28 13:00:06,006 - uvicorn.error - INFO - Started server process [45693] [server.py:84]
2025-09-28 13:00:06,006 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-28 13:00:06,007 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-28 13:03:24,938 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-28 13:03:25,881 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-28 13:03:26,068 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:03:26,423 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:03:26,452 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:03:26,460 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:03:26,735 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:04:35,619 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:04:35,622 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:04:35,682 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:02,324 - app.main - INFO - Root endpoint accessed [main.py:57]
2025-09-28 13:07:16,675 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:16,677 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:16,715 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:16,958 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:16,984 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:20,824 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:20,830 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:20,855 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:20,981 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:21,001 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:23,580 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:23,584 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:23,610 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:23,713 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:23,732 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:24,609 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:24,612 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:24,650 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:24,745 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:24,754 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:25,670 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:25,674 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:25,705 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:25,796 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:25,811 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:27,331 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:27,336 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:27,885 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:28,059 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:28,091 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:32,982 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:07:32,984 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:07:34,017 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:34,539 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:07:34,590 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:25:48,171 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-28 13:25:48,307 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-28 13:25:48,415 - app.main - INFO - API routers included [main.py:53]
2025-09-28 13:25:48,416 - uvicorn.error - INFO - Started server process [50675] [server.py:84]
2025-09-28 13:25:48,416 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-28 13:25:48,417 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-28 13:26:11,378 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-28 13:26:13,000 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-28 13:26:13,107 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:14,206 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:14,237 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:14,266 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:14,486 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:22,255 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:26:22,285 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:26:22,700 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:23,320 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:26:23,358 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:41:21,416 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-28 13:41:22,538 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-28 13:41:22,611 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:41:23,579 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:41:23,589 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:41:24,210 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:41:24,215 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:43:14,338 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:43:14,358 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:43:14,424 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:43:14,541 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:43:14,549 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:46:24,851 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:46:24,854 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:46:24,877 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:46:25,603 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:46:25,646 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:46:27,209 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:47:58,472 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:47:58,476 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:47:58,505 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:47:58,658 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:47:58,671 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:01,225 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:02,486 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:03,799 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:15,306 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:15,318 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:15,356 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:48:15,512 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:56:11,305 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:56:11,618 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:56:11,650 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:59:32,876 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 13:59:32,887 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 13:59:32,985 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:59:33,243 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 13:59:33,287 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:01:57,380 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:01:59,551 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:02:00,824 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:02:02,154 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:02:05,417 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:03:51,310 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:04:13,960 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:04:18,194 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:04:18,205 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:04:18,219 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:04:18,293 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:04:33,263 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 14:04:33,266 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 14:04:33,342 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:09:10,850 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:09:17,185 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-09-28 14:17:31,433 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-28 14:17:31,534 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-28 14:17:31,534 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-28 14:17:31,535 - uvicorn.error - INFO - Finished server process [50675] [server.py:94]
2025-09-28 14:17:43,134 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-28 14:17:43,134 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-28 14:17:43,218 - app.main - INFO - API routers included [main.py:53]
2025-09-28 14:17:43,220 - uvicorn.error - INFO - Started server process [56905] [server.py:84]
2025-09-28 14:17:43,220 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-28 14:17:43,221 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-28 14:17:50,964 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-09-28 14:17:51,064 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-09-28 14:17:51,065 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-09-28 14:17:51,065 - uvicorn.error - INFO - Finished server process [56905] [server.py:94]
2025-09-28 14:17:55,051 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-09-28 14:17:55,052 - app.main - INFO - CORS middleware configured [main.py:41]
2025-09-28 14:17:55,200 - app.main - INFO - API routers included [main.py:53]
2025-09-28 14:17:55,203 - uvicorn.error - INFO - Started server process [57014] [server.py:84]
2025-09-28 14:17:55,203 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-09-28 14:17:55,204 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-09-28 14:18:41,533 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-09-28 14:18:41,936 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-09-28 14:21:05,390 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-09-28 14:21:05,475 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-09-28 14:21:05,715 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:53:50,342 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 18:53:50,342 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 18:53:50,499 - app.main - INFO - API routers included [main.py:53]
2025-10-07 18:53:50,501 - uvicorn.error - INFO - Started server process [303812] [server.py:84]
2025-10-07 18:53:50,501 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 18:53:50,502 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 18:53:58,804 - app.routers.users - INFO - Attempting login for user: testerwizard02@gmail.com [users.py:113]
2025-10-07 18:53:58,862 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-10-07 18:53:59,252 - app.routers.users - INFO - Login successful for testerwizard02@gmail.com [users.py:170]
2025-10-07 18:53:59,324 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:53:59,558 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:53:59,580 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:53:59,627 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:53:59,695 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:55:05,314 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:55:11,795 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:55:16,050 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 18:57:53,295 - app.main - INFO - Root endpoint accessed [main.py:57]
2025-10-07 19:06:08,415 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:06:08,430 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:06:08,450 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:06:08,599 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:06:13,367 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:09:45,908 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:09:45,917 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:09:46,146 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:09:46,726 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:09:46,732 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:09:46,830 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:09:46,840 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:10:43,811 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:10:43,814 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:10:44,633 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:10:44,635 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:10:45,325 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:10:45,327 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:10:46,219 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:10:46,223 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:10:47,464 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:10:47,503 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:10:47,510 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:10:47,609 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:10:47,611 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:11:10,648 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:11:10,677 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:11:10,680 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:11:10,778 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:11:10,779 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:11:12,675 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:11:17,670 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:11:20,860 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:11:20,877 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:11:20,881 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:11:20,975 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:11:20,977 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:11:22,143 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:11:22,151 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:11:22,153 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:11:22,247 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:11:22,248 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:15:24,817 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:15:24,919 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:15:24,919 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:15:24,919 - uvicorn.error - INFO - Finished server process [303812] [server.py:94]
2025-10-07 19:16:50,305 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:16:50,305 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:16:50,479 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:16:50,481 - uvicorn.error - INFO - Started server process [310479] [server.py:84]
2025-10-07 19:16:50,481 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:16:50,482 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:16:53,469 - app.routers.users - INFO - Attempting login for user: a@gmail.com [users.py:113]
2025-10-07 19:16:53,518 - app.routers.users - WARNING - Login failed: User with email a@gmail.com not found [users.py:118]
2025-10-07 19:32:24,308 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:32:24,373 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:32:24,502 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:24,845 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:24,858 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:24,874 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:25,021 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:33,888 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:32:33,895 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:32:34,045 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:34,367 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:46,117 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-10-07 19:32:46,853 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:55,571 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:32:55,582 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:224]
2025-10-07 19:32:55,725 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:32:56,023 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:20,570 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:20,700 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:36,017 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:36,039 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:36,095 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:36,220 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:268]
2025-10-07 19:33:38,387 - app.routers.users - INFO - Attempting to log out user [users.py:245]
2025-10-07 19:33:38,388 - app.routers.users - INFO - User logged out successfully [users.py:253]
2025-10-07 19:33:42,121 - app.routers.users - INFO - Attempting to refresh access token [users.py:192]
2025-10-07 19:33:42,122 - app.routers.users - WARNING - Refresh failed: No refresh token provided [users.py:195]
2025-10-07 19:33:52,977 - app.routers.users - INFO - Attempting login for user: a@gmail.com [users.py:113]
2025-10-07 19:33:52,985 - app.routers.users - WARNING - Login failed: User with email a@gmail.com not found [users.py:118]
2025-10-07 19:33:59,180 - app.routers.users - INFO - Attempting login for user: a@gmail.com [users.py:113]
2025-10-07 19:33:59,182 - app.routers.users - WARNING - Login failed: User with email a@gmail.com not found [users.py:118]
2025-10-07 19:35:17,341 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:35:17,442 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:35:17,442 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:35:17,443 - uvicorn.error - INFO - Finished server process [310479] [server.py:94]
2025-10-07 19:35:28,190 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:35:28,190 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:35:28,463 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:35:28,467 - uvicorn.error - INFO - Started server process [314373] [server.py:84]
2025-10-07 19:35:28,468 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:35:28,469 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:35:32,895 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:35:32,896 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:35:33,127 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:35:33,130 - uvicorn.error - INFO - Started server process [314463] [server.py:84]
2025-10-07 19:35:33,131 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:35:33,131 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:35:34,137 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:35:34,238 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:35:34,238 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:35:34,238 - uvicorn.error - INFO - Finished server process [314463] [server.py:94]
2025-10-07 19:35:40,138 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:35:40,139 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:35:40,472 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:35:40,475 - uvicorn.error - INFO - Started server process [314490] [server.py:84]
2025-10-07 19:35:40,475 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:35:40,476 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:35:50,422 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:35:50,522 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:35:50,523 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:35:50,523 - uvicorn.error - INFO - Finished server process [314490] [server.py:94]
2025-10-07 19:35:55,067 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:35:55,068 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:35:55,236 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:35:55,238 - uvicorn.error - INFO - Started server process [314652] [server.py:84]
2025-10-07 19:35:55,238 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:35:55,239 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:35:55,440 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:35:55,541 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:35:55,542 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:35:55,543 - uvicorn.error - INFO - Finished server process [314652] [server.py:94]
2025-10-07 19:36:00,482 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:36:00,483 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:36:00,705 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:36:00,707 - uvicorn.error - INFO - Started server process [314676] [server.py:84]
2025-10-07 19:36:00,707 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:36:00,707 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:36:48,590 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:36:48,713 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:36:48,713 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:36:48,713 - uvicorn.error - INFO - Finished server process [314676] [server.py:94]
2025-10-07 19:36:53,586 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:36:53,587 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:36:53,845 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:36:53,847 - uvicorn.error - INFO - Started server process [314930] [server.py:84]
2025-10-07 19:36:53,847 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:36:53,847 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:37:59,693 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:37:59,798 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:37:59,799 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:37:59,799 - uvicorn.error - INFO - Finished server process [314930] [server.py:94]
2025-10-07 19:38:05,580 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:38:05,581 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:38:05,922 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:38:05,924 - uvicorn.error - INFO - Started server process [315341] [server.py:84]
2025-10-07 19:38:05,924 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:38:05,924 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:38:36,848 - app.routers.users - INFO - Attempting unified login for: a@gmail.com [users.py:113]
2025-10-07 19:38:36,977 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-10-07 19:38:37,721 - app.routers.users - INFO - Unified login successful for a@gmail.com as admin [users.py:183]
2025-10-07 19:38:38,214 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:38:38,217 - app.routers.users - WARNING - Refresh failed: No refresh token provided [users.py:210]
2025-10-07 19:38:38,293 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:38:38,297 - app.routers.users - WARNING - Refresh failed: No refresh token provided [users.py:210]
2025-10-07 19:39:12,314 - app.routers.users - INFO - Attempting unified login for: testerwizard02@gmail.com [users.py:113]
2025-10-07 19:39:12,769 - app.routers.users - INFO - Unified login successful for testerwizard02@gmail.com as user [users.py:183]
2025-10-07 19:39:13,023 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:39:13,176 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:39:13,179 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:39:13,280 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:39:13,285 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:39:54,948 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:39:54,950 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:39:57,396 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:39:57,404 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:39:58,172 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:39:58,177 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:01,524 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:40:08,378 - app.routers.users - INFO - Attempting unified login for: a@gmail.com [users.py:113]
2025-10-07 19:40:08,929 - app.routers.users - INFO - Unified login successful for a@gmail.com as admin [users.py:183]
2025-10-07 19:40:09,411 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:09,420 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:09,486 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:40:09,512 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:09,514 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:09,624 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:09,627 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:14,828 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:14,872 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:27,477 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:40:44,070 - app.routers.users - INFO - Attempting unified login for: a@gmail.com [users.py:113]
2025-10-07 19:40:44,521 - app.routers.users - INFO - Unified login successful for a@gmail.com as admin [users.py:183]
2025-10-07 19:40:44,921 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:44,924 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:45,007 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:40:45,037 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:45,039 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:40:45,193 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:40:45,204 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:42:53,837 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:42:53,849 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:42:54,101 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:42:54,267 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:42:54,372 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:42:54,372 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:42:54,373 - uvicorn.error - INFO - Finished server process [315341] [server.py:94]
2025-10-07 19:43:13,512 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:43:13,513 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:43:13,665 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:43:13,667 - uvicorn.error - INFO - Started server process [317471] [server.py:84]
2025-10-07 19:43:13,667 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:43:13,667 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:46:32,728 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:46:32,828 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:46:32,829 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:46:32,830 - uvicorn.error - INFO - Finished server process [317471] [server.py:94]
2025-10-07 19:46:37,178 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:46:37,179 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:46:37,402 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:46:37,404 - uvicorn.error - INFO - Started server process [318010] [server.py:84]
2025-10-07 19:46:37,405 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:46:37,405 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:48:09,681 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:48:09,782 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:48:09,783 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:48:09,787 - uvicorn.error - INFO - Finished server process [318010] [server.py:94]
2025-10-07 19:48:14,683 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:48:14,685 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:48:14,980 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:48:14,984 - uvicorn.error - INFO - Started server process [318546] [server.py:84]
2025-10-07 19:48:14,986 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:48:14,989 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:48:58,530 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:48:58,631 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:48:58,631 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:48:58,634 - uvicorn.error - INFO - Finished server process [318546] [server.py:94]
2025-10-07 19:49:03,165 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:49:03,165 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:49:03,324 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:49:03,325 - uvicorn.error - INFO - Started server process [318832] [server.py:84]
2025-10-07 19:49:03,325 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:49:03,326 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:49:32,220 - uvicorn.error - INFO - Shutting down [server.py:264]
2025-10-07 19:49:32,320 - uvicorn.error - INFO - Waiting for application shutdown. [on.py:67]
2025-10-07 19:49:32,321 - uvicorn.error - INFO - Application shutdown complete. [on.py:76]
2025-10-07 19:49:32,321 - uvicorn.error - INFO - Finished server process [318832] [server.py:94]
2025-10-07 19:49:35,309 - app.main - INFO - Black Germ FastAPI application initialized [main.py:31]
2025-10-07 19:49:35,309 - app.main - INFO - CORS middleware configured [main.py:41]
2025-10-07 19:49:35,513 - app.main - INFO - API routers included [main.py:53]
2025-10-07 19:49:35,514 - uvicorn.error - INFO - Started server process [318906] [server.py:84]
2025-10-07 19:49:35,514 - uvicorn.error - INFO - Waiting for application startup. [on.py:48]
2025-10-07 19:49:35,515 - uvicorn.error - INFO - Application startup complete. [on.py:62]
2025-10-07 19:49:38,130 - app.routers.users - INFO - Attempting unified login for: a@gmail.com [users.py:113]
2025-10-07 19:49:38,168 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version [bcrypt.py:622]
Traceback (most recent call last):
  File "/home/eddy/Documents/we_page/black_germ_backend/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-10-07 19:49:38,639 - app.routers.users - INFO - Unified login successful for a@gmail.com as admin [users.py:183]
2025-10-07 19:49:39,123 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:49:39,128 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:49:39,213 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:49:39,237 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:49:39,241 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:49:39,373 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:49:39,380 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:49:52,849 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:50:06,849 - app.routers.users - INFO - Attempting unified login for: a@gmail.com [users.py:113]
2025-10-07 19:50:07,312 - app.routers.users - INFO - Unified login successful for a@gmail.com as admin [users.py:183]
2025-10-07 19:50:07,633 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:50:07,635 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:50:07,672 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
2025-10-07 19:50:07,691 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:50:07,692 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:50:07,793 - app.routers.users - INFO - Attempting to refresh access token [users.py:207]
2025-10-07 19:50:07,794 - app.routers.users - INFO - Access token refreshed successfully for testerwizard02@gmail.com [users.py:239]
2025-10-07 19:50:29,205 - app.routers.users - INFO - Fetching user info for testerwizard02@gmail.com [users.py:283]
